In [1]:
import pandas as pd

# Pandas Series

In [2]:
paises = pd.Series(['Perú','Chile','Colombia','Ecuador'])
paises

0        Perú
1       Chile
2    Colombia
3     Ecuador
dtype: object

In [3]:
paises = pd.Series(['Perú','Chile','Colombia','Ecuador'],index=[1,7,10,30])
paises

1         Perú
7        Chile
10    Colombia
30     Ecuador
dtype: object

In [4]:
dict = {1:'Perú',7:'Chile',10:'Colombia',30:'Ecuador'}
pd.Series(dict)

1         Perú
7        Chile
10    Colombia
30     Ecuador
dtype: object

# Pandas DataFrame

In [5]:
dict = {
    'pais':['Perú','Chile','Colombia','Ecuador'],
    'pbi':[183,170,160,150],
    'habitantes':[33,22,22,50]
}
df_paises = pd.DataFrame(dict,index=[1,7,10,30])
df_paises

        pais  pbi  habitantes
1       Perú  183          33
7      Chile  170          22
10  Colombia  160          22
30   Ecuador  150          50

In [6]:
df_paises.columns

Index(['pais', 'pbi', 'habitantes'], dtype='object')

In [7]:
df_paises.index

Index([1, 7, 10, 30], dtype='int64')